name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Unit tests
      run: npm run test:unit

    - name: E2E tests
      uses: cypress-io/github-action@v2
      with:
        start: npm run preview
        config: baseUrl=http://localhost:5050
        wait-on: 'http://localhost:5050'
        wait-on-timeout: 60
   
  Deploy:
    needs: Tests

    runs-on: ubuntu-latest

    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install
      run: npm install

    - name: Build
      run: npm run build -- --base=/comparador-renda-fixa/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist