name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm install
    - name: Unit tests
      run: npm run test:unit
    - name: E2E tests
      uses: cypress-io/github-action@v2
      with:
        start: npm run dev
        config: baseUrl=http://localhost:3000
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 60
        